# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_desc', models.TextField(blank=True, null=True)),
                ('educationandexp', models.TextField(blank=True, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('jobref', models.URLField(blank=True, max_length=250, null=True)),
                ('joburl', models.URLField(blank=True, max_length=250, null=True)),
                ('job_summary', models.TextField(blank=True, null=True)),
                ('knowledge', models.TextField(blank=True, null=True)),
                ('language_certificates', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('FR', 'FR'), ('EN', 'EN')], default='EN', max_length=2)),
                ('name', models.URLField(blank=True, max_length=250, null=True)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('salarymin', models.CharField(blank=True, max_length=40, null=True)),
                ('salarymax', models.CharField(blank=True, max_length=40, null=True)),
                ('salarytype', models.CharField(blank=True, max_length=20, null=True)),
                ('tweeted', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
    ]
