# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityjobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='jobname',
        ),
    ]
