# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityjobs', '0002_auto_20160508_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
