# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityjobs', '0003_auto_20160508_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobref',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
