# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityjobs', '0004_delete_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.TextField(blank=True, null=True)),
                ('languagecert', models.TextField(blank=True, null=True)),
                ('educationandexp', models.TextField(blank=True, null=True)),
                ('company_desc', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True, null=True)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityjobs.Job')),
            ],
        ),
    ]
