# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityjobs', '0004_auto_20160508_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
