# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityjobs', '0005_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='languagecert',
            new_name='language_certificates',
        ),
    ]
