# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityjobs', '0005_auto_20160509_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expirydate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='postdate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
