# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityjobs', '0006_auto_20160512_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_desc',
        ),
        migrations.RemoveField(
            model_name='job',
            name='educationandexp',
        ),
        migrations.RemoveField(
            model_name='job',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='job',
            name='language_certificates',
        ),
    ]
