# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salarytype', models.CharField(max_length=250)),
                ('knowledge', models.TextField()),
                ('language_certificates', models.TextField()),
                ('educationandexp', models.TextField()),
                ('company_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joburl', models.URLField(max_length=250)),
                ('expirydate', models.DateField()),
                ('salarymax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=150)),
                ('jobref', models.CharField(max_length=30)),
                ('job_summary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplois.Job'),
        ),
    ]
