# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
