# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0005_auto_20160105_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salarymax',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
