# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0006_auto_20160105_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
