# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0002_auto_20160526_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='COMPANYDESC',
            new_name='COMPANY_DESC',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='LANGUAGECERT',
            new_name='LANGUAGE_CERTIFICATES',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='JOBSUMMARY',
            new_name='JOB_SUMMARY',
        ),
    ]
