# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 05:22
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='salarytype',
        ),
        migrations.RemoveField(
            model_name='job',
            name='timestamps',
        ),
        migrations.AddField(
            model_name='job',
            name='salarytype',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['jobref', 'position', 'pub_date__month']),
        ),
    ]
