# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0003_auto_20160105_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='salarymin',
        ),
        migrations.AddField(
            model_name='job',
            name='salarymin',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
