# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0004_auto_20160105_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salarytype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
